# Custom Language File for Launcher Customizer

[ejs.app]
title = "SCP Earth Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/5UP3RTH30B4G/SCP-Earth-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/"

[ejs.settings]
sourceGithubLink = "https://github.com/5UP3RTH30B4G/SCP-Earth-Launcher"
supportLink = "https://github.com/5UP3RTH30B4G/SCP-Earth-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur SCP Earth"
welcomeDescription = "description"
welcomeDescCTA = "Plus que quelque clic"
